---
- name: Configure Cisco Switch Hostname
  hosts: all
  gather_facts: false
  
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: ansible
    ansible_password: Cisco123
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: Cisco123

  tasks:
    - name: Set hostname on the switch
      cisco.ios.ios_hostname:
        hostname: AnsibleSetHostname
      register: output

    - name: Save the running config
      cisco.ios.ios_config:
        save_when: modified